### PR TITLE
1.0 ttypes

### PR DESCRIPTION
**Pull request by thobbs**

### CODE REVIEW

**Comment by thobbs** [comment]
I tested this against Cassandra 0.7.10 through 1.1.0-beta2.  I'm not sure if there was any other cleanup you needed to do on the x-version-compat branch.

It seemed to me that including the ttypes module for each version of Cassandra was a decent way to simultaneously offer support for all versions.  Let me know if you have other ideas on how it should be done.

**Comment by thepaul** [comment]
Did you find something that made it necessary to include the ttypes module for each version?  My research from earlier indicated that everything could be made to work with only the generated thrift code from Cassandra after #3953.  Everything that cassandra 0.7 needs to do should be doable through that, as long as the onus is on the user to know how what attributes and methods should be usable.

**Comment by thobbs** [comment]
The main motivation (at least for usage with OpsCenter or libraries that want to work with multiple versions of C*) was having the thrift_spec from each version available, particularly for KsDef, CfDef, and ColumnDef.  This lets you easily determine what fields are valid for the current version, avoiding invalid kwargs without having to update a hard-coded list for every new release of Cassandra.

This does rely on particulars of what Thrift generates, which could certainly change in the future.  If there were another way to easily introspect what the valid fields are for different API versions, I would prefer that.  Maybe the thrift_spec could allow you to set a range of supported API versions for each attribute?

I feel like #3953 solves half of the problems, but the remaining "onus" could also be removed fairly easily.

Thoughts?

**Comment by thepaul** [comment]
I guess the right solution depends on what exactly is needed in determining "valid" fields.  Fields that can be set on a CfDef without causing an error?  Fields that can be inspected without causing an error?  Fields which might be set by the server?  Fields which are honored by the server?  Fields which will actually be transmitted to the server if they are set?

Those are all disjoint sets.

If all we want is to avoid invalid kwargs without having to update hard-coded lists, that should be easy: allow users to specify any kwargs. All will be set as attributes on CfDef objects, and only the ones which the local Thrift definition understands will get transmitted, and only the ones which the remote Thrift definition understands will be received, and only the ones which the remote Cassandra cares about will be used.

**Comment by thobbs** [comment]
Well, just avoiding invalid kwargs isn't really all I had in mind.  Ideally, we have three nice properties:
1.  It's possible to set any attribute that's supported by the current API
2.  It's easy to tell which attributes are supported
3.  If you supply a bad attribute, you get feedback about it, either from Telephus or Cassandra

> ... only the ones which the local Thrift definition understands will get transmitted ...

The CfDef definition itself controls what gets transmitted, so having the different versions of ttypes is one way to control this.  Of course, 3953 makes it so that all past and present attributes will be transmitted, so that strategy won't always work.

Thinking about it now, I guess 3953 breaks this strategy enough that separate attribute lists are the only real option.  I'll pull out the other ttypes modules and put in a post 3953 one.  Is there even any need to care about the API version after that?  It doesn't seem like it.

**Comment by thepaul** [comment]
> 1 . It's possible to set any attribute that's supported by the current API

Ok, that one's pretty easy.

> 2 . It's easy to tell which attributes are supported

Even without 3953, you can't really get this in an automated way.  There were already attributes which were present in the IDL, but wholly ignored by Cassandra.  It doesn't seem useful to differentiate those from attributes which aren't in the IDL.

> 3 . If you supply a bad attribute, you get feedback about it, either from Telephus or Cassandra

Again, what definition of "bad" would you use?  "Unrecognized by local thrift", "unrecognized by remote thrift", or "actually meaningful to Cassandra"? My argument is that the first is the only one that could reasonably be detected before 3953, and that the third is the only actually useful one, and that those two are only weakly correlated.

> The CfDef definition itself controls what gets transmitted, so having the different versions of ttypes is one way to control this. Of course, 3953 makes it so that all past and present attributes will be transmitted, so that strategy won't always work.

So, you want to have a fine-grained control over which attributes actually get transmitted?

> Thinking about it now, I guess 3953 breaks this strategy enough that separate attribute lists are the only real option. I'll pull out the other ttypes modules and put in a post 3953 one. Is there even any need to care about the API version after that? It doesn't seem like it.

Just enough to report it to the user when necessary. I can't think of anything else.

**Comment by thobbs** [comment]
> So, you want to have a fine-grained control over which attributes actually get transmitted?

No, ideally you would get feedback in the form of an invalid kwarg before the transmission occurs rather than transform it silently; it seemed that you might have thought this was already happening post-3953, so I was addressing that.

Anyways, moving along, would you be agreeable to the following changes?
-  Remove c{07, 08, 10} and the `latest` module, replacing them with a single post-3953 set of ttypes.py and Cassandra.py
-  Remove thrift_api references in protocol.py and pool.py, instead referring directly to ttypes
-  Keep what's currently in translate.py, since it's still useful regardless of the other changes

**Comment by thepaul** [comment]
Yeah, that all sounds good to me. We should probably also take out the "self.ttypes" references in pool and protocol, and use the module directly (I think that's what you meant, but just to be explicit).

Also, I just realized the x-version-compat branch I pushed wasn't properly rebased- has a rogue "wip" commit in there. I've now pushed the one that I thought was there originally, as "x-version-compat-b" and rebased your changes on top of it as "1.0-ttypes". If you want to reset your branch to that one and build on top of that, that would help keep history clean :)

Thanks for this.

**Comment by thobbs** [comment]
Alright, will do.  No problem.

**Pull request closed without merging**
