### PR TITLE
Remove translate

### PR DESCRIPTION
**Pull request by thobbs**
This pull request removes translate.py and all version-specific translation.

With the last pull request, I thought that the translation layer would still be useful, but I now think it's more of a hassle than it's worth.  In Cassandra 0.7, you have to set the `replication_factor` attribute of a `KsDef`.  In 1.1, the request will fail if you set it.  This means that at the least, we would need to track those versions and change behavior in Telephus based on the api_version.  Furthermore, `replication_factor` isn't even needed with NetworkTopologyStrategy, so it just adds a possibility of cluttering things there.

The translation later might have been useful for the 0.7 to 0.8 transition, but I think it's time for it to go.  It provides very little benefit at this point and has the downside of being potentially confusing.

### CODE REVIEW

**Comment by thepaul** [comment]
Also, are you sure that a system_add_keyspace fails against 1.1 when KsDef.replication_factor is set?  It doesn't seem to, and I can't think of any reason why it should.

**Comment by thobbs** [comment]
Hmm, you're right about 1.1 not caring about KsDef.replication_factor being set.  That negates some of my concerns.  In light of that, are you in favor of pulling out translate.py or not?  I'm still in favor of removing it.

The reason that I removed api_version is that the same information is easily discoverable through a describe_version() call when needed. We can save an extra API call when initializing new connections by removing it.  I left the describe_version() call in ManagedThriftClientProtocol.setupConnection() as a sort of "test" operation for the connection, but I could go either way on keeping or removing it.  (Pool.prep_connection() already calls describe_ring() every time.)

Good idea on using defer.succeed().

**Comment by thepaul** [comment]
I don't remember—is it very simple from the client's perspective to make a describe_version call to a specific backend, or do all calls just get queued for the next available backend?

If it's easy, we might as well take it out, like you say.  I'm mostly ambivalent about translate.py.

**Comment by thobbs** [comment]
> I don't remember—is it very simple from the client's perspective to make a describe_version call to a specific backend, or do all calls just get queued for the next available backend?

They just get queued if you're using a pool, so you need to use a normal CassandraClient to figure out the api version of a single node.  That doesn't concern me too greatly because there's not currently a good reason to have version-specific behavior in a mixed cluster.  For example, you don't want to create keyspaces while your cluster is half 0.7 and half 0.8.

**Comment by thepaul** [comment]
Fair enough.

**Pull request merged**
