### PR TITLE
Bumped version number as the ~ in 0.8.0~beta1 throws off setuptools.

### PR DESCRIPTION
**Pull request by wehriam**

### CODE REVIEW

**Comment by thepaul** [comment]
How does it throw off setuptools?  Any specifics?

**Comment by wehriam** [comment]
Sorry to be vague. When Telephus is listed as a dependency in `install_requires` the `~` character causes an error. So, this fails:

```
install_requires = [
    'Routes>=1.12.3',
    'Twisted>=11.1.0',
    'thrift>=0.8.0',
    'ujson>=1.15',
    'cityhash>=0.2.0',
    'telephus>=1.0.0~beta1',
    'txroutes>=0.0.2'],
```

with:

```
error in hiitrack setup command: 'install_requires' must be a string or list of strings
containing valid project/version requirement specifiers
```

While this succeeds:

```
install_requires = [
    'Routes>=1.12.3',
    'Twisted>=11.1.0',
    'thrift>=0.8.0',
    'ujson>=1.15',
    'cityhash>=0.2.0',
    'telephus>=1.0.0',
    'txroutes>=0.0.2'],
```

Some quick digging found that Distribute only allows `[-A-Za-z0-9_.]` my guess is setuptools is similar: http://packages.python.org/distribute/pkg_resources.html#requirements-parsing

**Comment by thepaul** [comment]
Ah, thanks for the info.

**Comment by thepaul** [comment]
(sorry, I had thought that these other commits were meant to be part of the pull request. my bad)

Keeping the beta modifier tacked on the version number for now; working on some changes to better support use with cassandra 1.0.

**Comment by wehriam** [comment]
No problem, they were not intended to be part of the pull request. You should keep the beta modifier but remove the "~" character as it is invalid.

**Comment by thepaul** [comment]
Right. I used _ here instead.

**Pull request closed without merging**
