### PR TITLE
Pooling rpc address

### PR DESCRIPTION
**Pull request by nickmbailey**
This pull request also includes the changes from the pull request: https://github.com/driftx/Telephus/pull/31

That request should be merged in first before reviewing this one.

The changes here should be pretty simple. Versions of cassandra > 0.7 include an rpc_address field in the output of describe_ring. When using describe ring for purposes of connection pooling/failover the rpc address should be used when attempting to connect to auto discovered nodes, assuming it is a good ip and not '0.0.0.0'.

There is an included unit test that should cover all added functionality. Additionally I've manually tested against both 0.7, and 0.8 where nodes had differing rpc and listen addresses.

### CODE REVIEW

**Comment by thepaul** [comment]
The test attached here won't work on top of #31- the c07.ttypes and c08.ttypes modules are no longer there.  Not that it matters that much, since Cassanova hasn't been maintained and probably won't work at all with CassandraClusterPoolTest.  Guess we need to change that to use ccm or dtests2 somehow.

Want to update the test, or tear it out, or just leave it as is?

The actual code looks good.

**Comment by nickmbailey** [comment]
Ah, I guess I still had built .pyc files for c08 and c07 around. The test doesn't actually have any need for cassanova since I'm just passing in raw thrift objects to the method. I just put it there cause its part of CassandraClusterPool. Maybe just make it a utility method at the top of pool.py and test it separately?

**Comment by thepaul** [comment]
Yeah, if it works on its own, it might be best to have a separate UnitTest subclass with just that test in it (that doesn't get nuked when Cassanova isn't present).

**Comment by nickmbailey** [comment]
Fixed and created new PR against unstable

**Pull request closed without merging**
